# Generated by Django 5.2.3 on 2025-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_tokan',
            new_name='email_token',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_email',
            new_name='is_email_verified',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
