# Generated by Django 5.2.3 on 2025-08-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size_variant',
            new_name='size_variant',
        ),
        migrations.RenameField(
            model_name='sizevariant',
            old_name='Size_name',
            new_name='size_name',
        ),
    ]
